version: '2.4'

services:

  deno_app:
    build:
      context: .
    command: denon
    ports:
      - '8000:8000'
    volumes:
      - .:/opt/deno_app:delegated
      - ./src/deps.ts:/opt/deno_app/src/deps.ts
